                                        ;;
                                     eval(
                                  %w[n=1;e
                               val$s=%q[v=
                            0;%!{ys:s"C4FC
                        wFdRd%KcT*?0Mqa4}4
                    5~PaYiO@o7{R04xy~PESfn
                kEFVvQRz?i%I3$QxP"}/9Xb3g6
          D,OC(~;ha#>0^m&4B~lg%efyJ}fXyblX
   B^paFazw^&fo{ZM/1_ZS6jK~DBGMzykZI"%,^.S
^X?PPtkHhJ@&NL)@WS;6XwQ3|b<(sGZQu&YbnQN9af
 ykds`?9Z=}Y<Z-V`Xot4n>x|{LaV_I7H7'HU+sd0a
 mk=g|Z:`HC}uoo($&<)"shC}/;F$v^&8?G(DXPE+g
                       d_Oa):~LzyhX/yHj}:5
                       8YEQcp0fi-6f{DA76F^
                       qT4nmiahFqpdxrXHOpA
                        MHB+XhG"$iXU_vZ)op
                        Dh4#o)4}/q"~Sg}~o:
                        %=1=r$snSZZ<^YD.R?
                        0{zSB9>;>DsK?@&yI_
                        zyqQMxZz=XXvT8Y</|
                        6eyg-*"}SPptyaz8ze
                        vf+MZhmio<L2,yLhEJ
                        nHO5_/R{^3052Ek|W~
                        FO|h&/+blxBr)|:p"Q
                        Fdw')*lQ)>|:)wTED:
                        *=hw*~ANT.L)Q6xUo^
                        !.bytes{|m|v=v*90+
                        m%93-1};b=[*0..7];
                        r=c=z=[7];9.upto(4
                        56){|s|b<<z+c=[*b[
                        v%s]||c][0,1];r+=z
                       =[*b[v%s]];v/=s}.ti
                       mes{|i|u=[81+s=v>>i
                       *6&63];t=d=0;z=32.c
                       hr;m=z*6561;(m[p||=
                      s]=?;;d+=r.pop;p+=(-
                      (d%4)%82+1).*1-d[2]*
                      2)until(p==s);m[p=u.
                     pop]==z&&u+=[p+1,p-1,
                     p-81,p+81,m[p]=?;]unt
                    il[]==u;n==i&&m.sub(/(
                   ;{5}#{z}*;;;.*);{5}/){$
                  1.gsub(?;){("#eval(%w[n=
                 #{(n+1)%9};eval$s=%q[#$s]
                #".+$s.tr"[]","")[t+=1]}+"
              ]*'')"}.rstrip.scan(
           /.{1,81}/){puts
         $&.rstrip}}]
           #]*'')
            ;
